package ikriti.natgeo.hb;
// Generated Oct 29, 2010 12:55:50 AM by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * EnumMemberStatus generated by hbm2java
 */
@Entity
@Table(name="enum_member_status"
    ,schema="public"
)
public class EnumMemberStatus  implements java.io.Serializable {


     private int id;
     private String status;
     private String description;
     private Set<Member> members = new HashSet<Member>(0);

    public EnumMemberStatus() {
    }

	
    public EnumMemberStatus(String status) {
        this.status = status;
    }
    public EnumMemberStatus(String status, String description, Set<Member> members) {
       this.status = status;
       this.description = description;
       this.members = members;
    }
   
     @SequenceGenerator(name="generator", allocationSize=1, sequenceName="enum_member_status_id_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    
    @Column(name="status", nullable=false)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
@OneToMany(cascade=CascadeType.ALL, fetch=FetchType.LAZY, mappedBy="enumMemberStatus")
    public Set<Member> getMembers() {
        return this.members;
    }
    
    public void setMembers(Set<Member> members) {
        this.members = members;
    }




}


