package ikriti.natgeo.hb;
// Generated Oct 29, 2010 12:55:50 AM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.SEQUENCE;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * MaParticipant generated by hbm2java
 */
@Entity
@Table(name="ma_participant"
    ,schema="public"
)
public class MaParticipant  implements java.io.Serializable {


     private int id;
     private Member member;
     private String height;
     private String weight;
     private String age;

    public MaParticipant() {
    }

    public MaParticipant(Member member, String height, String weight, String age) {
       this.member = member;
       this.height = height;
       this.weight = weight;
       this.age = age;
    }
   
     @SequenceGenerator(name="generator", allocationSize=1, sequenceName="ma_participant_id_seq")@Id @GeneratedValue(strategy=SEQUENCE, generator="generator")
    
    @Column(name="id", unique=true, nullable=false)
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="member")
    public Member getMember() {
        return this.member;
    }
    
    public void setMember(Member member) {
        this.member = member;
    }
    
    @Column(name="height", length=10)
    public String getHeight() {
        return this.height;
    }
    
    public void setHeight(String height) {
        this.height = height;
    }
    
    @Column(name="weight", length=10)
    public String getWeight() {
        return this.weight;
    }
    
    public void setWeight(String weight) {
        this.weight = weight;
    }
    
    @Column(name="age", length=10)
    public String getAge() {
        return this.age;
    }
    
    public void setAge(String age) {
        this.age = age;
    }




}


